# Generated by Django 5.1.3 on 2024-11-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='Content_type',
            new_name='content_type',
        ),
    ]
